version: 0.2

phases:
  # pre_build:
  #   commands:
  #     - echo Logging into DockerHub
  build:
    commands:
      - echo Build started on `date`
      - echo "Installing Terraform"
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      - echo "Configuring project"
      - echo "PROJECT_PATH=$PROJECT_PATH"
      - cd $PROJECT_PATH
      - terraform init
      - terraform plan
      - # terraform $TERRAFORM_ACTION -auto-approve
